import type { Metadata } from "next";
import { Montserrat, Space_Grotesk } from "next/font/google";
import "./globals.css";

const grotesque = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata: Metadata = {
  title: "ielts-course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${grotesque.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
